id: os_erase_contents_and_settings_disable
title: "Ensure Allow Erase All Content and Settings is set to Disabled"
discussion: |
  Erase all contents and settings _MUST_ be disabled on institutionally owned iOS devices.
check: " "
fix: |
  This is implemented by a Configuration Profile.
references:
  cce:
    - CCE-94437-1
  cci: 
    - CCI-000366
  800-53r5:
    - CM-6
    - CM-7
    - CM-7(1)
  sfr:
    - 'FMT_SMF.1.1 #47'
  disa_stig:
    - AIOS-18-016000
  cis:
    benchmark:
      - 3.2.1.12 (level 1 - Institutionally-Owned Devices)
    controls v8:
      - 4.1
iOS:
  - "18.0"
tags:
  - ios
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - cis_lvl1_enterprise
  - cis_lvl2_enterprise
  - cisv8
  - ios_stig
supervised: true
mobileconfig: true
mobileconfig_info:
  com.apple.applicationaccess:
    allowEraseContentAndSettings: false