id: os_install_configuration_profile_disable
title: "Ensure Allow Installing Configuration Profiles is Set to Disabled"
discussion: |
  Configuration profiles _MUST_ be installed via an organization's MDM.
check: " "
fix: |
  This is implemented by a Configuration Profile.
references:
  cce:
  - CCE-95484-2
  cci:
  - N/A
  800-53r5:
  - CM-6
  - CM-7
  - CM-7(1)
  800-53r4:
  - N/A
  sfr:
  - N/A
  disa_stig:
  - N/A
  indigo:
    - N/A
  cis:
    benchmark:
    - 3.2.1.15 (level 1 - Institutionally-Owned Devices)
    controls v8:
    - 4.1
iOS:
- "26.0"
tags:
- ios
- cis_lvl1_enterprise
- cis_lvl2_enterprise
- cisv8
- cnssi-1253_moderate
- cnssi-1253_low
- cnssi-1253_high
severity: medium
supervised: true
mobileconfig: true
mobileconfig_info:
  com.apple.applicationaccess:
    allowUIConfigurationProfileInstallation: false
