id: os_pairing_non_configurator_hosts_disable
title: Ensure Allow pairing with non-Configurator hosts is set to Disabled
discussion: |
  Host pairing with a non-Configurator host _MUST_ be disabled.
check: ' '
fix: |
  This is implemented by a Configuration Profile.
references:
  cce:
  - CCE-95503-9
  cci:
  - N/A
  800-53r5:
  - CM-6
  - CM-7
  - CM-7(1)
  sfr:
  - N/A
  disa_stig:
  - N/A
  indigo:
    - N/A
iOS:
- '26.0'
tags:
- ios
- 800-53r5_low
- 800-53r5_moderate
- 800-53r5_high
- cis_lvl2_enterprise
- cisv8
- cnssi-1253_moderate
- cnssi-1253_low
- cnssi-1253_high
supervised: true
mobileconfig: true
mobileconfig_info:
  com.apple.applicationaccess:
    allowHostPairing: false
