id: os_pairing_non_configurator_hosts_disable
title: "Ensure Allow pairing with non-Configurator hosts is set to Disabled"
discussion: |
  Host pairing with a non-Configurator host _MUST_ be disabled.
check: " "
fix: |
  This is implemented by a Configuration Profile.
references:
  cce:
    - CCE-94454-6
  cci: 
    - CCI-000366
  800-53r5:
    - CM-6
    - CM-7
    - CM-7(1)
  sfr:
    - 'FMT_MOF_EXT.1.2 #47'
  disa_stig:
    - AIOS-18-016500
  indigo:
    - ANNEX K
  cis:
    benchmark:
      - 3.2.1.20 (level 2 - Institutionally-Owned Devices)
    controls v8:
      - 4.8
iOS:
  - "18.0"
tags:
  - ios
  - ios_stig
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - cis_lvl2_enterprise
  - cisv8
  - indigo_base
  - indigo_high
supervised: true
mobileconfig: true
mobileconfig_info:
  com.apple.applicationaccess:
    allowHostPairing: false